session_name: BI_Github_Pages
windows:
  - window_name: Bullish-Intelligence.github.io
    layout: main-vertical
    options:
      main-pane-width: 20%
    panes:
      - shell_command:
          - cd ~/Documents/Notes/Projects/Bullish-Intelligence.github.io
          # - nvim Notes.md ToDo.md
          - open-project
      - shell_command:
          - tmux resizep -y 85%
          - filelist-open "startup_files.txt" Bullish-Intelligence.github.io
        focus: true
      - clear
